"""empty message

Revision ID: e522ed85edd7
Revises: fa51a304b9e4
Create Date: 2022-12-12 12:32:19.707071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e522ed85edd7'
down_revision = 'fa51a304b9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'])

    with op.batch_alter_table('dailies', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'])
        batch_op.drop_column('checklist')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'])

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'])
        batch_op.drop_column('checklist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('dailies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
